### ISSUE TITLE
Broken links for power nodes

### ISSUE THREAD

**Issue by henry422** [openinframap/styles#60] opened 2019-11-02 23:29 UTC
Nodes of e.g. power=transformer or switch are displayed, but the link in the popup when click on the node in the map is wrongly generated as a link to a way: 
https://openstreetmap.org/way/1700420094
when the object is a node, correct link would be:
https://openstreetmap.org/node/1700420094

https://openinframap.org/#17.9/46.824745/12.805094
Click on any generator or switch smbole and then on the link in the popup.

Data (properties) of the nodes are also not shown in the popup (besides the id), probably because of the same underlying reason.

**Comment by russss** [comment] 2019-11-02 23:36
This is a duplicate of openinframap/web#6

**Closed by russss** 2019-11-02 23:36 UTC
