### ISSUE TITLE
Some power plants do not display their output capacity

### ISSUE THREAD

**Issue by Gazer75** [openinframap/styles#7] opened 2017-12-24 00:45 UTC
Not sure why this is happening to some plants.
They are tagged with plant:output:electricity

Only thing I can think of is that there is no landuse tag which would be kind of silly for something that is inside a mountain.
Also missing the power:source

**Comment by gustavecha** [comment] 2017-12-24 09:03
Hi

It's ont really an openinframap issue but an OSM data issue.
Plants may ne described as relations when not enclosed by a fence.
https://wiki.openstreetmap.org/wiki/Tag:power%3Dplant

Power:source is not a used tag. Do you think of plant:source ?

**Comment by Gazer75** [comment] 2017-12-24 12:16
Is this not enough to have it display the output on the openinframap?
https://www.openstreetmap.org/way/545991307

**Comment by gustavecha** [comment] 2017-12-24 12:27
Yes, the poly shouldn't be tagged with power=plant since penstocks, dams, tunnels and even lakes are members of a power=plant + type=site relation.

Only poly fences surrounding closed plants like nuke or combustion plants should be areas with power=plant on it

Renders have to deal with this

**Comment by Gazer75** [comment] 2017-12-24 12:30
Well I've noticed that even a relation with all the parts of the plant is completely ignored by the map.

And what about this: https://www.openstreetmap.org/way/548627805
It's a power plant in a building, nothing more. If I can't tag that as a power=plant then I'm very confused about the use of the power=plant tag.

**Comment by Gazer75** [comment] 2017-12-24 12:40
My point is that as long as there is a poly with an output value it should be possible to display it on the map. It is already displaying the name, so why not the output? That't my point of this issue.

**Comment by Gazer75** [comment] 2017-12-24 12:54
Could it be that it is not accepting **plant:output:electricity**, but instead simply expect the generic **plant:output**?

**Comment by gustavecha** [comment] 2017-12-24 17:23
I agree for render polygons with output value
The issue you raise is real

Regarding how plant relation are made, wiki stands to add every infeastructure required by the plant to run
No particular roles are defined. Many of them can be retrieved by looking at tags on members themselves (dam is a dam, generators are generators and so on)
https://wiki.openstreetmap.org/wiki/Tag:power%3Dplant#Dispersed_facilities_power_plants

**Comment by Gazer75** [comment] 2017-12-28 08:20
So far the only way I've found the map displaying the output is to make a multipoly relation.

If I tag a simple polygon as a plant with the appropriate values it will not show up. 
This is very confusing as I've seen other plants done that way and they show up just fine.

**Comment by gustavecha** [comment] 2017-12-28 22:03
I understand the point about capacity displaying.
But since tagging isn't done specifically for render, displaying something on a render doesn't make data right.


The real issue is about map style and answers are in this file :
https://github.com/openinframap/styles/blob/master/power.mss
On line 150, "#power_plant[zoom>=9][output>100]," indicates that only plants with a higher capacity than 100MW will be shown with their capacity.

Furthermore, in https://github.com/openinframap/styles/blob/master/mapping.yml
#power_plant class is clearly defined as "all polygons with power=plant", then all relations which are not multipolygons are ignored.
This is understandable : how and where would we display a label or capacity on a power plant like such ?
https://www.openstreetmap.org/relation/7844811

**Comment by Gazer75** [comment] 2017-12-29 01:24
I understand about tagging for renderer, but when I didn't understand why some showed and some didn't, I got confused. Thanks for clearing that up.

So the map style is set to completely ignore any output value below 100 MW? Or is it only at z9 and out that those are displayed?
This is not my experience. At z9 the names of the plants show along with their generation method. Then at z12 it will show the output.
If only 100MW+ plants are displayed then that will exclude a lot of plants from showing output.
Only 80 of our over 1600 hydro plants can do over 100MW. Reduce that limit to 50 and the number goes up to 142 :)
A simple multipoly relation with a polygon will display the output regardless of value it seems.

In a site relation that defines the turbines it would be possible to put the name in the middle of them maybe? The relation above do not set the roles on the elements so its hard to know.
If this was more clear on the wiki I am sure we would get more consistent tagging.

**Comment by russss** [comment] 2017-12-31 11:35
OK so as I understand it this issue is about not rendering `type=site power=plant` relations? This is a known bug and a slightly fiddly one to fix, but I am aware of it.

**Comment by Gazer75** [comment] 2017-12-31 11:46
The issue is that if I do a simple polygon and tag it with power=plant, plant:output:electricity, name and so on it will display the name but not the effect. It will even display the name at z9 if the output is over 100MW. But never show the value at z12.

**Comment by russss** [comment] 2017-12-31 11:49
Can you give me an example link to openinframap where this happens? I can't seem to reproduce it in the UK :)

**Comment by Gazer75** [comment] 2017-12-31 11:50
well I'll have to edit one back then cause I've moved all to multipoly relations I think, cause that works just fine :)

**Comment by Gazer75** [comment] 2017-12-31 11:57
Updated this just now: https://www.openstreetmap.org/way/401860890 and we'll see...

**Comment by Gazer75** [comment] 2017-12-31 12:59
Looks like low outputs are not displayed at all?
https://www.openstreetmap.org/relation/7849015

**Comment by russss** [comment] 2017-12-31 13:12
That's a relation which as I mentioned before isn't supported yet.

**Comment by Gazer75** [comment] 2017-12-31 13:22
No its not. That is the exact same relation as I've used on other plants and they show up just fine.

**Comment by gustavecha** [comment] 2017-12-31 13:25
This is a multipolygon, only type=site relation aren't supported yet.

**Comment by russss** [comment] 2018-01-01 18:12
A multipolygon is a relation - the system at the moment doesn't support relations at all. That's why this isn't being rendered.

**Comment by russss** [comment] 2018-01-01 19:15
OK, it turns out my previous comment was wrong - I didn't realise imposm3 does some magic to handle multipolygon relations automatically.

The bug with your 9MW power station was because of an issue with my power value conversion code which I fixed in 141d1f7.

Handling `type=site` relations is covered by issue #11.

**Closed by russss** 2018-01-01 19:15 UTC
Labels: bug, style
