### ISSUE TITLE
Render switch and location.transition on poles

### ISSUE THREAD

**Issue by pyrog** [openinframap/styles#41] opened 2019-03-07 15:32 UTC
#### Manual
Called _"Interrupteur Aérien Contrôlé Manuellement (IACM)"_ in France.
Examples: [node/6317122630](https://www.openstreetmap.org/node/6317122630#map=16/46.6122/5.7310) [Pictures](https://commons.wikimedia.org/w/index.php?search=insource%3AOSM_ID%3D6317122630&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%22namespaces%22%3A%5B6%2C12%2C14%2C100%2C106%2C0%5D%7D&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1&ns0=1&searchToken=9hbnjffk8cqk4m51hwyr0eu5h), [node/6304665001](https://www.openstreetmap.org/node/6304665001#map=16/46.5967/5.7399) [Pictures](https://commons.wikimedia.org/w/index.php?search=insource%3AOSM_ID%3D6304665001&title=Special%3ASearch&profile=advanced&fulltext=1&advancedSearch-current=%7B%22namespaces%22%3A%5B6%2C12%2C14%2C100%2C106%2C0%5D%7D&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1&ns0=1)

* `power=pole`
* `switch=*` (usually `mechanical` or `yes`)

#### Remotely controlled
Called _"Interrupteur Aérien Télécommandé (IAT)"_ in France.
Example: [node/6304664998](https://www.openstreetmap.org/node/6304664998#map=16/46.5992/5.7369) [Pictures](https://commons.wikimedia.org/w/index.php?search=insource%3AOSM_ID%3D6304664998&title=Special%3ASearch&profile=advanced&fulltext=1&advancedSearch-current=%7B%22namespaces%22%3A%5B6%2C12%2C14%2C100%2C106%2C0%5D%7D&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1&ns0=1)
* `power=pole`
* `switch=*` (usually `mechanical` or `yes`)
* `remotely_controllable=*` (usually `radio`)

### Transition on pole
Called _"Remontée Aéro Souterraine (RAS)"_ in France.
Example: [node/6229041425](https://www.openstreetmap.org/node/6229041425#map=19/46.56791/5.76684) [Pictures](https://commons.wikimedia.org/w/index.php?search=insource%3AOSM_ID%3D6229041425&title=Special%3ASearch&profile=advanced&fulltext=1&advancedSearch-current=%7B%22namespaces%22%3A%5B6%2C12%2C14%2C100%2C106%2C0%5D%7D&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1&ns0=1)
* `power=pole`
* `location:transition=*` (usually `yes`)

**Comment by russss** [comment] 2019-03-07 15:34
This is a duplicate of #19 and #17.

**Closed by russss** 2019-03-07 15:34 UTC

**Comment by pyrog** [comment] 2019-03-19 16:28
Transition on poles / towers are rendered.
Thank you 😊

[Pole
<img width="285" alt="Capture d’écran 2019-03-19 à 17 19 17" src="https://user-images.githubusercontent.com/2158081/54623099-2b4e0400-4a6b-11e9-8fde-ac61423f20ae.png">](https://openinframap.org/#17.9/46.366065/5.802652)

[Tower
<img width="248" alt="Capture d’écran 2019-03-19 à 17 25 48" src="https://user-images.githubusercontent.com/2158081/54623617-2b9acf00-4a6c-11e9-9d9f-2f6eb57e372b.png">
](https://openinframap.org/#17.9/46.691962/5.562799)
